# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.5.0
  slack: circleci/slack@4.13.1

# Define jobs
jobs:
  say-hello:
    docker:
      # Specify the version you desire here
      - image: cimg/base:current
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  notify-slack:
    docker:
      - image: cimg/android:2024.01-ndk
    steps:
      - checkout
      - run:
          name: "Export Commit"
          command: "echo 'Exporting commit details'"
      - slack/notify:
          custom: |
            {
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "plain_text",
                     "text": "Zofeur Deployment Successful :tada:",
                     "emoji": true
                   }
                 },
                 {
                   "type": "header",
                   "text": {
                     "type": "plain_text",
                     "text": "Release notes",
                     "emoji": true
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "plain_text",
                     "text": "*Release contains* hello github",
                     "emoji": true
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "Download Build from Firebase."
                   },
                   "accessory": {
                     "type": "button",
                     "text": {
                       "type": "plain_text",
                       "text": "Download",
                       "emoji": true
                     },
                     "value": "click_me_123",
                     "url": "https://appdistribution.firebase.dev/i/51a009a32bc58e82",
                     "action_id": "button-action"
                   }
                 }
               ]
             }
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          ignore_errors: true
          mentions: ''

# Orchestrate jobs using workflows
workflows:
  version: 2
  build-and-notify:
    jobs:
      - say-hello
      - notify-slack:
          requires:
            - say-hello
          context: slack-secrets
